"use client";

import { useActionState } from "react";
import type { AnnouncementDirection } from "@/generated/prisma/enums";
import { saveAnnouncement, type AnnouncementFormState } from "../actions";

type Announcement = { id: string; isActive: boolean; content: string; speed: number; background: string; textColor: string; direction: AnnouncementDirection; link: string | null };
const initialState: AnnouncementFormState = {};

export function AnnouncementEditor({ announcement }: { announcement?: Announcement }) {
  const [state, action, pending] = useActionState(saveAnnouncement, initialState);
  return <form action={action} className="mt-8 space-y-7">{announcement && <input name="id" type="hidden" value={announcement.id} />}<section className="rounded-xl border border-primary-100 bg-white p-5 sm:p-6"><h2 className="font-display text-xl font-semibold">Announcement</h2><div className="mt-5 space-y-5"><label className="flex items-center gap-3 text-sm font-medium text-primary-800"><input className="h-4 w-4 accent-primary-950" defaultChecked={announcement?.isActive ?? false} name="isActive" type="checkbox" />Display this announcement on the storefront</label><label className="block text-sm font-medium text-primary-800">Message<input className="input mt-2" defaultValue={announcement?.content ?? "Complimentary delivery on orders over NGN 50,000"} maxLength={500} name="content" required /></label><label className="block text-sm font-medium text-primary-800">Destination link <span className="font-normal text-primary-500">(optional)</span><input className="input mt-2" defaultValue={announcement?.link ?? ""} name="link" placeholder="/shop or https://example.com" type="text" /></label></div></section><section className="rounded-xl border border-primary-100 bg-white p-5 sm:p-6"><h2 className="font-display text-xl font-semibold">Appearance and motion</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><ColorField label="Background" name="background" value={announcement?.background ?? "#2e2032"} /><ColorField label="Text colour" name="textColor" value={announcement?.textColor ?? "#ffffff"} /><label className="text-sm font-medium text-primary-800">Speed (seconds)<input className="input mt-2" defaultValue={announcement?.speed ?? 40} max="1000" min="10" name="speed" type="number" required /></label><label className="text-sm font-medium text-primary-800">Direction<select className="input mt-2" defaultValue={announcement?.direction === "RIGHT" ? "right" : "left"} name="direction"><option value="left">Left</option><option value="right">Right</option></select></label></div></section>{state.error && <p className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{state.error}</p>}{state.success && <p className="rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-700" role="status">{state.success}</p>}<button className="rounded-lg bg-primary-950 px-5 py-3 text-sm font-semibold text-white hover:bg-primary-800 disabled:opacity-60" disabled={pending} type="submit">{pending ? "Saving…" : "Save announcement"}</button></form>;
}
function ColorField({ label, name, value }: { label: string; name: string; value: string }) { return <label className="text-sm font-medium text-primary-800">{label}<span className="mt-2 flex h-[46px] items-center rounded-lg border border-primary-200 px-2"><input className="h-7 w-10 cursor-pointer border-0 bg-transparent p-0" defaultValue={value} name={name} type="color" /><span className="ml-2 text-xs font-normal text-primary-600">{value}</span></span></label>; }
