"use client";

import { useActionState } from "react";
import { saveStore, type StoreFormState } from "../actions";

type Store = { id: string; name: string; address: string; city: string | null; state: string | null; country: string; phone: string | null; email: string | null; latitude: string | number | null; longitude: string | number | null; openingHours: unknown; isActive: boolean };
const initialState: StoreFormState = {};
export function StoreForm({ store }: { store?: Store }) { const [state, action, pending] = useActionState(saveStore, initialState); const openingHours = store?.openingHours ? JSON.stringify(store.openingHours) : ""; return <form action={action} className="mt-5 grid gap-4 sm:grid-cols-2">{store && <input name="id" type="hidden" value={store.id} />}<Field label="Store name" name="name" defaultValue={store?.name ?? ""} required /><Field label="Country" name="country" defaultValue={store?.country ?? ""} required /><label className="sm:col-span-2 text-sm font-medium text-primary-800">Address<textarea className="input mt-2 min-h-20" name="address" defaultValue={store?.address ?? ""} required /></label><Field label="City" name="city" defaultValue={store?.city ?? ""} /><Field label="State" name="state" defaultValue={store?.state ?? ""} /><Field label="Phone" name="phone" defaultValue={store?.phone ?? ""} /><Field label="Email" name="email" type="email" defaultValue={store?.email ?? ""} /><Field label="Latitude" name="latitude" type="number" step="any" defaultValue={store?.latitude?.toString() ?? ""} /><Field label="Longitude" name="longitude" type="number" step="any" defaultValue={store?.longitude?.toString() ?? ""} /><label className="sm:col-span-2 text-sm font-medium text-primary-800">Opening hours JSON <span className="font-normal text-primary-500">(optional)</span><textarea className="input mt-2 min-h-20 font-mono text-xs" name="openingHours" defaultValue={openingHours} placeholder='{"monday":"09:00-18:00"}' /></label><label className="flex items-center gap-3 text-sm font-medium text-primary-800"><input className="h-4 w-4 accent-primary-950" defaultChecked={store?.isActive ?? true} name="isActive" type="checkbox" />Active</label>{state.error && <p className="sm:col-span-2 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{state.error}</p>}{state.success && <p className="sm:col-span-2 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700" role="status">{state.success}</p>}<button className="w-fit rounded-lg bg-primary-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60" disabled={pending} type="submit">{pending ? "Saving..." : store ? "Save changes" : "Add store"}</button></form>; }
function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="text-sm font-medium text-primary-800">{label}<input className="input mt-2" {...props} /></label>; }
