import Link from "next/link";
import { Role } from "@/generated/prisma/client";
import { requireAdminPage } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { AdminShell } from "../components/admin-shell";

export const dynamic = "force-dynamic";
export default async function JournalPage() {
  const user = await requireAdminPage([Role.GENERAL_ADMIN, Role.SOCIAL_TEAM]);
  const posts = await prisma.blogPost.findMany({ where: user.role === Role.SOCIAL_TEAM ? { authorId: user.id } : undefined, select: { id: true, title: true, slug: true, status: true, updatedAt: true, author: { select: { name: true } } }, orderBy: { updatedAt: "desc" } });
  return <AdminShell user={user}><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-accent-700">Content</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight">Journal</h1><p className="mt-2 text-sm text-primary-600">{user.role === Role.SOCIAL_TEAM ? "Create and maintain your journal articles." : "Review and manage all storefront journal articles."}</p></div><Link className="rounded-lg bg-primary-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-800" href="/admin/journal/new">New article</Link></header><section className="mt-8 overflow-hidden rounded-xl border border-primary-100 bg-white"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-primary-100 bg-primary-50 text-xs uppercase tracking-wide text-primary-600"><tr><th className="px-5 py-4">Article</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Author</th><th className="px-5 py-4">Updated</th><th className="px-5 py-4"><span className="sr-only">Edit</span></th></tr></thead><tbody className="divide-y divide-primary-100">{posts.map((post) => <tr key={post.id}><td className="px-5 py-4"><p className="font-semibold">{post.title}</p><p className="mt-1 text-xs text-primary-500">/{post.slug}</p></td><td className="px-5 py-4"><span className="rounded-full bg-primary-100 px-2.5 py-1 text-xs font-semibold text-primary-700">{post.status}</span></td><td className="px-5 py-4 text-primary-700">{post.author.name}</td><td className="px-5 py-4 text-primary-700">{post.updatedAt.toLocaleDateString("en-NG", { dateStyle: "medium" })}</td><td className="px-5 py-4 text-right"><Link className="font-medium text-primary-800 hover:text-primary-950" href={`/admin/journal/${post.id}`}>Edit</Link></td></tr>)}{posts.length === 0 && <tr><td className="px-5 py-12 text-center text-primary-600" colSpan={5}>No articles yet. Create the first journal entry.</td></tr>}</tbody></table></div></section></AdminShell>;
}
