"use client";

import { useActionState } from "react";
import { ProductBadge, ProductStatus } from "@/generated/prisma/enums";
import { createProduct, updateProduct, type ProductFormState } from "../actions";
import { ProductImageUpload } from "./product-image-upload";

type ProductValue = { id: string; name: string; slug: string; description: string | null; price: string | number; compareAtPrice: string | number | null; stock: number; categoryId: string; status: ProductStatus; badge: ProductBadge | null; isBestSeller: boolean; images: { url: string; publicId?: string | null }[]; retailers: { retailerId: string; externalProductUrl: string; isAvailable: boolean }[] };
type Category = { id: string; name: string };
type Retailer = { id: string; name: string; country: string | null };
const initialState: ProductFormState = {};

export function ProductEditor({ categories, retailers, product }: { categories: Category[]; retailers: Retailer[]; product?: ProductValue }) {
  const action = product ? updateProduct : createProduct;
  const [state, formAction, pending] = useActionState(action, initialState);
  const value = (field: keyof ProductValue) => product?.[field] ?? "";

  return <form action={formAction} className="mt-8 space-y-7">
    {product && <input name="id" type="hidden" value={product.id} />}
    <fieldset className="rounded-xl border border-primary-100 bg-white p-5 sm:p-6"><legend className="px-1 font-display text-xl font-semibold">Basic information</legend><div className="mt-4 grid gap-5 sm:grid-cols-2"><Field label="Product name" name="name" defaultValue={String(value("name"))} required /><Field label="Slug" name="slug" defaultValue={String(value("slug"))} hint="Lowercase words separated by hyphens." required /><label className="sm:col-span-2 text-sm font-medium text-primary-800">Description<textarea className="input mt-2 min-h-32" defaultValue={String(value("description"))} name="description" /></label><label className="text-sm font-medium text-primary-800">Category<select className="input mt-2" defaultValue={String(value("categoryId"))} name="categoryId" required><option value="" disabled>Select a category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="text-sm font-medium text-primary-800">Status<select className="input mt-2" defaultValue={String(value("status") || ProductStatus.DRAFT)} name="status"><option value={ProductStatus.DRAFT}>Draft</option><option value={ProductStatus.ACTIVE}>Active</option></select></label></div></fieldset>
    <fieldset className="rounded-xl border border-primary-100 bg-white p-5 sm:p-6"><legend className="px-1 font-display text-xl font-semibold">Pricing and inventory</legend><div className="mt-4 grid gap-5 sm:grid-cols-3"><Field label="Price (NGN)" name="price" type="number" min="1" defaultValue={String(value("price"))} required /><Field label="Compare-at price" name="compareAtPrice" type="number" min="1" defaultValue={String(value("compareAtPrice"))} /><Field label="Stock quantity" name="stock" type="number" min="0" defaultValue={String(value("stock") || 0)} required /><label className="text-sm font-medium text-primary-800">Badge<select className="input mt-2" defaultValue={String(value("badge"))} name="badge"><option value="">No badge</option><option value={ProductBadge.NEW}>New</option><option value={ProductBadge.BESTSELLER}>Bestseller</option></select></label><label className="flex items-center gap-3 self-end pb-2 text-sm font-medium text-primary-800"><input className="h-4 w-4 accent-primary-950" defaultChecked={Boolean(value("isBestSeller"))} name="isBestSeller" type="checkbox" />Feature in Best Sellers</label></div></fieldset>
    <fieldset className="rounded-xl border border-primary-100 bg-white p-5 sm:p-6"><legend className="px-1 font-display text-xl font-semibold">Where to buy online</legend><p className="mt-2 text-sm text-primary-600">Add the verified product page for each retailer. Customers complete checkout externally.</p><div className="mt-5 space-y-4">{retailers.map((retailer) => { const link = product?.retailers.find((item) => item.retailerId === retailer.id); return <div className="grid gap-3 rounded-lg border border-primary-100 p-4 sm:grid-cols-[1fr_2fr_auto] sm:items-end" key={retailer.id}><div><p className="font-semibold text-primary-950">{retailer.name}</p><p className="text-xs text-primary-500">{retailer.country ?? "Country not listed"}</p><input name="retailerId" type="hidden" value={retailer.id} /></div><label className="text-sm font-medium text-primary-800">Product URL<input className="input mt-2" defaultValue={link?.externalProductUrl ?? ""} name={`retailerUrl:${retailer.id}`} placeholder="https://..." type="url" /></label><label className="flex items-center gap-2 pb-3 text-sm font-medium text-primary-800"><input className="h-4 w-4 accent-primary-950" defaultChecked={link?.isAvailable ?? true} name={`retailerAvailable:${retailer.id}`} type="checkbox" />Available</label></div>; })}{retailers.length === 0 && <p className="text-sm text-primary-600">Add a retailer before linking this product.</p>}</div></fieldset>
    <fieldset className="rounded-xl border border-primary-100 bg-white p-5 sm:p-6"><legend className="px-1 font-display text-xl font-semibold">Primary image</legend><p className="mt-2 text-sm text-primary-600">Images are uploaded privately through the admin server and stored in Cloudinary.</p><ProductImageUpload initialUrl={product?.images[0]?.url} initialPublicId={product?.images[0]?.publicId} /></fieldset>
    {state.error && <p className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{state.error}</p>}
    <button className="rounded-lg bg-primary-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-primary-800 disabled:opacity-60" disabled={pending} type="submit">{pending ? "Saving…" : product ? "Save changes" : "Create product"}</button>
  </form>;
}
function Field({ label, hint, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string; hint?: string }) { return <label className="text-sm font-medium text-primary-800">{label}<input className="input mt-2" {...props} />{hint && <span className="mt-1 block text-xs font-normal text-primary-500">{hint}</span>}</label>; }
