import { Role } from "@/generated/prisma/enums";
import { requireAdminPage } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { AdminShell } from "../components/admin-shell";
import { StoreForm } from "./components/store-form";
import { toggleStore } from "./actions";

export const dynamic = "force-dynamic";
export default async function StoresPage() { const user = await requireAdminPage([Role.GENERAL_ADMIN, Role.SALES_TEAM]); const stores = await prisma.store.findMany({ orderBy: [{ country: "asc" }, { state: "asc" }, { city: "asc" }, { name: "asc" }] }); return <AdminShell user={user}><header><p className="text-xs font-semibold uppercase tracking-[0.2em] text-accent-700">Purchasing</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight">Stores</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-primary-600">Maintain the public directory of physical stores. This directory does not represent product-level stock.</p></header><section className="mt-8 rounded-xl border border-primary-100 bg-white p-5 sm:p-6"><h2 className="font-display text-xl font-semibold">Add store</h2><StoreForm /></section><section className="mt-8 overflow-hidden rounded-xl border border-primary-100 bg-white"><div className="border-b border-primary-100 px-5 py-4"><h2 className="font-display text-xl font-semibold">Store directory</h2></div><div className="divide-y divide-primary-100">{stores.map((store) => <article className="grid gap-4 px-5 py-5 lg:grid-cols-[1fr_auto]" key={store.id}><div><div className="flex flex-wrap items-center gap-3"><h3 className="font-semibold text-primary-950">{store.name}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${store.isActive ? "bg-green-50 text-green-700" : "bg-primary-100 text-primary-600"}`}>{store.isActive ? "Active" : "Inactive"}</span></div><p className="mt-1 text-sm text-primary-600">{store.address} · {[store.city, store.state, store.country].filter(Boolean).join(", ")}</p><StoreForm store={{ ...store, latitude: store.latitude?.toString() ?? null, longitude: store.longitude?.toString() ?? null }} /></div><form action={toggleStore}><input name="id" type="hidden" value={store.id} /><button className="h-fit text-sm font-semibold text-primary-700 underline-offset-4 hover:text-primary-950 hover:underline" type="submit">{store.isActive ? "Deactivate" : "Activate"}</button></form></article>)}{stores.length === 0 && <p className="px-5 py-8 text-sm text-primary-600">No stores have been added.</p>}</div></section></AdminShell>; }
